### ISSUE TITLE
Create README.md, and LICENSE

### ISSUE THREAD

**Issue by dariusstrasel** [mechamecho/DataDrivenTesting#18]

**Comment by dariusstrasel** [comment]
@mechamecho Add this repo to this analyzer and checkout the results. ;)

http://demos.algorithmia.com/github-readme-analyzer/

**Comment by mechamecho** [comment]
That is pretty interesting, so much that can be improved! Thanks for sharing this tool!

**Comment by mechamecho** [comment]
The readme analyzer suggested adding an Overview section so I did. Now it is suggesting to remove it since popular repositories don't have that section. 
I am not sure, if I should remove it or not.

**Comment by dariusstrasel** [comment]
Thats pretty ironic. I'd say keep the overview.

**Comment by dariusstrasel** [comment]
License suggestion is in PR: https://github.com/mechamecho/DataDrivenTesting/pull/21

Im thinking we just use an MIT license.

**Comment by mechamecho** [comment]
Alright, do you think I should close this issue?

**Comment by dariusstrasel** [comment]
Yes. I'll go ahead.
